### ISSUE TITLE
E-gineering Agenda

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/reactjsconsulting#71]
# When 

Tuesday-Thursday, August 17-19th 9:00am to 4:00pm 
Suite opens at 8:30 each morning 
Lunch about 11:30 🌮
Afternoon refreshments each day 🍩

# Format

Mob programming something realistic! 😀

# Key topics

JS fundamentals
React fundamentals
React Router
Automated testing
Mock APIs
Advanced React (time allowing)

# TODO

- [x] Add form
- [x] Create about page
- [x] Routing / Navigation
- [x] Reusable components
- [x] Consume open source component - react-toastr for notifications on save
- [x] Extract add to separate page
- [x] Handle edge cases via conditional JSX (show message when no inventory)
- [x] Edit form
- [x] React-query
- [x] Context
- [ ] Loading state
- [ ] Automated testing
- [ ] Load large dataset and discuss perf options
- [ ] Use suspense and React.Lazy to lazy load routes
- [ ] Validation
- [ ] Error Boundaries
- [ ] A11y
- [ ] Derived State - Filter or sort list
- [ ] Barrels for shortening imports
- [ ] Handle 404s
- [ ] Style active links
- [ ] CSS modules and inline styles
- [ ] Immer for immutable state management
- [ ] Functional setState when using existing state
- [x] Destructuring props in func signature
- [x] Destructuring to streamline render calls
- [ ] Create a custom hook (useIsMobile)
- [ ] Uncontrolled forms via refs
