### ISSUE TITLE
Southwest Airlines Agenda

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/reactjsconsulting#8]
# Agenda

- [x] [Intro](https://github.com/coryhouse/rjc/issues/2)
- [x] [Development Environment](https://github.com/coryhouse/rjc/issues/3)
- [x] [JavaScript intro](https://github.com/coryhouse/rjc/issues/11)
- [x] What should we build today?
  - [x] Idea: Display list of flights, pick one, display selection. Allow removing selection. Navigate between home and booking page.
  - [x] Have a preferred UI library?
- [x] [Modern JS](https://github.com/coryhouse/rjc/issues/4)
- [x] [Intro to React](https://github.com/coryhouse/rjc/issues/10)
- [x] [Redux](https://github.com/coryhouse/rjc/issues/7)

## If time
- [ ] [React design patterns](https://github.com/coryhouse/rjc/issues/1)
- [x] [Automated Testing](https://github.com/coryhouse/rjc/issues/6)
- [ ] [Reusable React Components ](https://github.com/coryhouse/rjc/issues/5)
- [ ] Code review or architectural review of existing code
